# -*- coding: utf-8 -*-
"""solver

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeW3B7jZ14tDIOEHmmArcJrIlRFryafW

**Task 2 and 3: Storing matrix and Forward Substitution**

This .py document contains the code for solving the equation by storing the matrix into coefficients A and B and running forward substitution.
"""

#Task 2: storage of matrix
import numpy as np

#Creating a function to define A and B
def storing_matrix(N_x, Delta_t, Delta_x, U):
#Creating placeholders for the coefficients A and B
  A=np.zeros((N_x-1))
  B=np.zeros((N_x-1))

#Setting up the code to work in both positive and negative directiob
  if U > 0:
    a= (1/Delta_t) + (U/Delta_x)
    b= -U/Delta_x
  else:
    a= (1/Delta_t) - (U/Delta_x)
    b= U/Delta_x

#Setting up the coefficients as constants within the domain as U is constant
  A[:]=a
  B[:]=b

#Returning A and B
  return A,B

#Task 3
#F=(1/Delta_t)*C_current[1:] #Setting up right hand side vector F

def forward_substitution(A, B, F, C_next): #defining a function to solve the linear system
  N_x= len(F) +1 #Total grid points, as F is one shorter than C_current


  for i in range (1,N_x): #Creating a loop to solve the linear system
    C_next[i]=(1/(A[i-1]))*(F[i-1]- B[i-1]*C_next[i-1])

  return C_next #Setting up the return of the C_next from this function
