# -*- coding: utf-8 -*-
"""Task 9_Test 3_Sensitivity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16aR6rpk_351p5n0aGLH4o7213mkwNu-S
"""

#Importing necessary function
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

#Importing functions defined in previous codes
from src.domain import setup_domain
from src.solver import storing_matrix, forward_substitution
from src.boundary import apply_inflow_boundary, apply_outflow_boundary

# Interpolation function
def interpolate_initial_conditions(sensor_data: pd.DataFrame, x_grid: np.ndarray) -> np.ndarray:
    x_sensor = sensor_data['Distance (m)'].to_numpy()
    C_sensor = sensor_data['Concentration (µg/m_ )'].to_numpy()
    idx = np.argsort(x_sensor)
    x_sorted = x_sensor[idx]
    C_sorted = C_sensor[idx]
    return np.interp(x_grid, x_sorted, C_sorted)

# Simulating the function
def run_simulation(U, Delta_x, Delta_t, L=20.0, T=300.0, C0=250.0):
    x_array, t_array, N_x, N_t = setup_domain(L, T, Delta_x, Delta_t)
    sensor_data = pd.read_csv('initial_conditions.csv', encoding='latin1')
    C_current = interpolate_initial_conditions(sensor_data, x_array)
    C_next = np.zeros_like(C_current)

    for n in range(1, N_t):
        A, B = storing_matrix(N_x, Delta_t, Delta_x, U)
        F=(1/Delta_t)*C_current[1:]
        C_next= forward_substitution(A, B, F, C_next)
        current_time = n * Delta_t
        apply_inflow_boundary(C_next, current_time, U)
        apply_outflow_boundary(C_next)
        C_current = C_next.copy()

    return x_array, C_current


#Settingup parameters
T = 5.0 * 60.0
L = 20.0
Delta_x_base = 0.2
Delta_t_base = 10.0
U_base = 0.1
C0 = 250.0

print("Running baseline simulation")
x_base, C_base = run_simulation(U_base, Delta_x_base, Delta_t_base, L, T, C0)

# Velocity sensitivity
print("\nRunning velocity sensitivity tests")
velocities = [0.05, 0.1, 0.2]
fig1, ax1 = plt.subplots(figsize=(10, 6))
ax1.plot(x_base, C_base, 'k--', linewidth=2, label=f'Baseline U={U_base} m/s')

for U in velocities:
    if U != U_base:
        x, C = run_simulation(U, Delta_x_base, Delta_t_base, L, T, C0)
        ax1.plot(x, C, label=f'U={U} m/s')
        diff = np.max(np.abs(C - np.interp(x, x_base, C_base)))
        print("Max difference from baseline μg/m³")

ax1.set_xlabel("Distance along river (m)")
ax1.set_ylabel("Pollutant concentration (μg/m³)")
ax1.set_title("Velocity Sensitivity Test")
ax1.grid(True)
ax1.legend()
plt.tight_layout()
plt.savefig("results/velocity_sensitivity.png")
plt.show()

# Spatial resolution sensitivity
print("Running spatial resolution sensitivity tests")
delta_x_values = [0.1, 0.2, 0.4]
fig2, ax2 = plt.subplots(figsize=(10, 6))

for dx in delta_x_values:
    x, C = run_simulation(U_base, dx, Delta_t_base, L, T, C0)
    label = f'Δx={dx} m' + (' (Baseline)' if dx == Delta_x_base else '')
    style = 'k--' if dx == Delta_x_base else '-'
    linewidth = 2 if dx == Delta_x_base else 1
    ax2.plot(x, C, style, linewidth=linewidth, label=label)
    print("Grid points = {len(x)}")

ax2.set_xlabel("Distance along river (m)")
ax2.set_ylabel("Pollutant concentration (μg/m³)")
ax2.set_title("Spatial Resolution Sensitivity Test")
ax2.grid(True)
ax2.legend()
plt.tight_layout()
plt.savefig("results/spatial_sensitivity.png")
plt.show()

# Temporal resolution sensitivity
print("\nRunning temporal resolution sensitivity tests")
delta_t_values = [5.0, 10.0, 20.0]
fig3, ax3 = plt.subplots(figsize=(10, 6))

for dt in delta_t_values:
    x, C = run_simulation(U_base, Delta_x_base, dt, L, T, C0)
    label = f'Δt={dt} s' + (' (Baseline)' if dt == Delta_t_base else '')
    style = 'k--' if dt == Delta_t_base else '-'
    linewidth = 2 if dt == Delta_t_base else 1
    ax3.plot(x, C, style, linewidth=linewidth, label=label)
    diff = np.max(np.abs(C - C_base))
    print(" Max difference from baseline μg/m³")

ax3.set_xlabel("Distance along river (m)")
ax3.set_ylabel("Pollutant concentration (μg/m³)")
ax3.set_title("Temporal Resolution Sensitivity Test")
ax3.grid(True)
ax3.legend()
plt.tight_layout()
plt.savefig("results/temporal_sensitivity.png")
plt.show()

# Combined difference plots
print("\nGenerating combined comparison plot")
fig4, (ax4a, ax4b, ax4c) = plt.subplots(3, 1, figsize=(10, 12))

for U in velocities:
    x, C = run_simulation(U, Delta_x_base, Delta_t_base, L, T, C0)
    diff = C - np.interp(x, x_base, C_base)
    ax4a.plot(x, diff, label=f'U={U} m/s')
ax4a.set_ylabel("Concentration difference (μg/m³)")
ax4a.set_title("Velocity Variation")
ax4a.grid(True)
ax4a.legend()

for dx in delta_x_values:
    if dx != Delta_x_base:
        x, C = run_simulation(U_base, dx, Delta_t_base, L, T, C0)
        C_interp = np.interp(x, x_base, C_base)
        diff = C - C_interp
        ax4b.plot(x, diff, label=f'Δx={dx} m')
ax4b.set_ylabel("Concentration difference (μg/m³)")
ax4b.set_title("Spatial Resolution Variation")
ax4b.grid(True)
ax4b.legend()

for dt in delta_t_values:
    if dt != Delta_t_base:
        x, C = run_simulation(U_base, Delta_x_base, dt, L, T, C0)
        diff = C - C_base
        ax4c.plot(x, diff, label=f'Δt={dt} s')
ax4c.set_xlabel("Distance along river (m)")
ax4c.set_ylabel("Concentration difference (μg/m³)")
ax4c.set_title("Temporal Resolution Variation")
ax4c.grid(True)
ax4c.legend()

plt.tight_layout()
plt.savefig("results/all_differences.png")
plt.show()

print(" - velocity_sensitivity.png")
print(" - spatial_sensitivity.png")
print(" - temporal_sensitivity.png")
print(" - all_differences.png")